/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twcn' at '10/1/16 8:01 PM' with Gradle 3.1
 *
 * @author twcn, @date 10/1/16 8:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
